#!/bin/sh
set -ex

JSONSCHEMA_OPTIONS="--jsonschema_out="
if [ "x$INPUT_OPTIONS" != 'x' ]; then
  JSONSCHEMA_OPTIONS=$JSONSCHEMA_OPTIONS$INPUT_OPTIONS
  JSONSCHEMA_OPTIONS=$JSONSCHEMA_OPTIONS":"
fi
JSONSCHEMA_OPTIONS=$JSONSCHEMA_OPTIONS$INPUT_OUTPUT_DIR

echo $JSONSCHEMA_OPTIONS
echo $INPUT_PROTO_PATH
echo $INPUT_PROTO_FILE

mkdir -p $INPUT_OUTPUT_DIR

protoc $JSONSCHEMA_OPTIONS --proto_path=$INPUT_PROTO_PATH $INPUT_PROTO_FILE

